eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://192.168.0.69:8761/eureka/}
  instance:
    instance-id: 192.168.0.69:${server.port}
    hostname: ${eureka_host:localhost}
