eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://192.168.0.69:8761/eureka/}
  instance:
    instance-id:  ${eureka_host:localhost}:${server.port}
    hostname: ${eureka_host:localhost}
