server:
  port: 8762

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PascalButterbach/config_server/
          clone-on-start: true
          skipSslValidation: true